### ISSUE TITLE
1.8.9

### ISSUE THREAD

**Issue by BlueXAyman** [amitojsingh366/Amitojs-Minecraft-RPC#1]
Hey mate, I really love your mod, I was wondering if you will ever make a 1.8.9 version, thanks.

**Comment by amitojsingh366** [comment]
Hmm never thought I would get even a single person to see this repo... But you're here so ill make you the 1.8.9 version *(won't be supporting it for long tho)* soon...

**Comment by BlueXAyman** [comment]
thank you
